
#---------------------------------------------------------------------
# Importing Libraries
print('---------------------------------------------------------------------------------')
print('Importing Libraries')
print('---------------------------------------------------------------------------------')
print('')

import numpy
import time
import tensorflow as tf
import os
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import math
from sklearn.ensemble import RandomForestClassifier
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
from keras.preprocessing import sequence
from keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import auc
from imblearn.over_sampling import RandomOverSampler
import shap
from scipy.special import softmax
np.random.seed(0)
from sklearn.model_selection import train_test_split
import sklearn
#---------------------------------------------------------------------
# Defining metric equations

print('---------------------------------------------------------------------------------')
print('Defining Metric Equations')
print('---------------------------------------------------------------------------------')
print('')
def print_feature_importances_shap_values(shap_values, features):
    '''
    Prints the feature importances based on SHAP values in an ordered way
    shap_values -> The SHAP values calculated from a shap.Explainer object
    features -> The name of the features, on the order presented to the explainer
    '''
    # Calculates the feature importance (mean absolute shap value) for each feature
    importances = []
    for i in range(shap_values.values.shape[1]):
        importances.append(np.mean(np.abs(shap_values.values[:, i])))
    # Calculates the normalized version
    importances_norm = softmax(importances)
    # Organize the importances and columns in a dictionary
    feature_importances = {fea: imp for imp, fea in zip(importances, features)}
    feature_importances_norm = {fea: imp for imp, fea in zip(importances_norm, features)}
    # Sorts the dictionary
    feature_importances = {k: v for k, v in sorted(feature_importances.items(), key=lambda item: item[1], reverse = True)}
    feature_importances_norm= {k: v for k, v in sorted(feature_importances_norm.items(), key=lambda item: item[1], reverse = True)}
    # Prints the feature importances
    for k, v in feature_importances.items():
        print(f"{k} -> {v:.4f} (softmax = {feature_importances_norm[k]:.4f})")


def ACC(TP,TN,FP,FN):
    Acc = (TP+TN)/(TP+FP+FN+TN)
    return Acc
def ACC_2 (TP, FN):
    ac = (TP/(TP+FN))
    return ac
def PRECISION(TP,FP):
    Precision = TP/(TP+FP)
    return Precision
def RECALL(TP,FN):
    Recall = TP/(TP+FN)
    return Recall
def F1(Recall, Precision):
    F1 = 2 * Recall * Precision / (Recall + Precision)
    return F1
def BACC(TP,TN,FP,FN):
    BACC =(TP/(TP+FN)+ TN/(TN+FP))*0.5
    return BACC
def MCC(TP,TN,FP,FN):
    MCC = (TN*TP-FN*FP)/(((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))**.5)
    return MCC
def AUC_ROC(y_test_bin,y_score):
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    auc_avg = 0
    counting = 0
    for i in range(n_classes):
      fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
      auc_avg += auc(fpr[i], tpr[i])
      counting = i+1
    return auc_avg/counting

def oversample(X_train, y_train):
    oversample = RandomOverSampler(sampling_strategy='minority')
    # Convert to numpy and oversample
    x_np = X_train.to_numpy()
    y_np = y_train.to_numpy()
    x_np, y_np = oversample.fit_resample(x_np, y_np)

    # Convert back to pandas
    x_over = pd.DataFrame(x_np, columns=X_train.columns)
    y_over = pd.Series(y_np)
    return x_over, y_over

#---------------------------------------------------------------------


print('---------------------------------------------------------------------------------')
print('Generating Stability Comparison')
print('---------------------------------------------------------------------------------')
print('')

### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF #### RF ####
print('---------------------------------------------------------------------------------')
print('RF SHAP CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')



Trial_1 =[
' Init_Win_bytes_backward',
' Destination Port',
' Fwd Packet Length Std',
' Flow IAT Max',
'Total Length of Fwd Packets',
' Fwd Packet Length Max',
' Flow IAT Mean',
' Fwd Header Length',
' Fwd IAT Std',
' Total Fwd Packets',
' Packet Length Mean',
' Packet Length Variance',
' Active Min',
' Bwd Header Length',
' Flow Duration',
' Packet Length Std',
' Bwd Packet Length Std',
'Fwd IAT Total',
'Bwd Packet Length Max',
' Fwd Packet Length Mean',
# ' Total Backward Packets',
# ' Subflow Bwd Packets',
# ' PSH Flag Count',
# ' Fwd Packet Length Min',
# ' Avg Bwd Segment Size',
# 'Init_Win_bytes_forward',
# ' Average Packet Size',
# ' Bwd Packet Length Min',
# ' Min Packet Length',
# 'Bwd IAT Total',
# ' Bwd IAT Mean',
# ' SYN Flag Count',
# ' Bwd IAT Max',
# 'Idle Mean',
# ' Bwd Packet Length Mean',
# 'Active Mean',
# ' Fwd IAT Max',
# ' Idle Min',
# ' Subflow Fwd Bytes',
# 'Fwd Packets/s',
# ' Fwd IAT Min',
# ' min_seg_size_forward',
# 'Subflow Fwd Packets',
# ' Max Packet Length',
# ' act_data_pkt_fwd',
# ' Flow IAT Min',
# ' Active Max',
# ' Bwd Packets/s',
# ' Idle Max',
# 'Fwd PSH Flags',
# ' Flow IAT Std',
# ' Idle Std',
# 'Flow Bytes/s',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' Flow Packets/s',
# ' Bwd Avg Packets/Bulk',
# ' Total Length of Bwd Packets',
# 'Bwd Avg Bulk Rate',
# ' Bwd IAT Min',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd IAT Mean',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Bwd IAT Std',
# 'FIN Flag Count',
# ' RST Flag Count',
# ' ACK Flag Count',
# ' Fwd Avg Bulk Rate',
# ' URG Flag Count',
# ' CWE Flag Count',
# ' ECE Flag Count',
# ' Down/Up Ratio',
# 'Fwd Avg Bytes/Bulk',
# ' Fwd Avg Packets/Bulk',
# ' Avg Fwd Segment Size'
]

Trial_2 =[
' Init_Win_bytes_backward',
' Destination Port',
' Fwd Packet Length Std',
' Flow IAT Max',
'Total Length of Fwd Packets',
' Fwd Packet Length Max',
' Flow IAT Mean',
' Fwd Header Length',
' Fwd IAT Std',
' Total Fwd Packets',
' Packet Length Mean',
' Packet Length Variance',
' Active Min',
' Bwd Header Length',
' Flow Duration',
' Packet Length Std',
' Bwd Packet Length Std',
'Fwd IAT Total',
'Bwd Packet Length Max',
' Fwd Packet Length Mean',
# ' Total Backward Packets',
# ' Subflow Bwd Packets',
# ' PSH Flag Count',
# ' Fwd Packet Length Min',
# ' Avg Bwd Segment Size',
# 'Init_Win_bytes_forward',
# ' Average Packet Size',
# ' Bwd Packet Length Min',
# ' Min Packet Length',
# 'Bwd IAT Total',
# ' Bwd IAT Mean',
# ' SYN Flag Count',
# ' Bwd IAT Max',
# 'Idle Mean',
# ' Bwd Packet Length Mean',
# 'Active Mean',
# ' Fwd IAT Max',
# ' Idle Min',
# ' Subflow Fwd Bytes',
# 'Fwd Packets/s',
# ' Fwd IAT Min',
# ' min_seg_size_forward',
# 'Subflow Fwd Packets',
# ' Max Packet Length',
# ' act_data_pkt_fwd',
# ' Flow IAT Min',
# ' Active Max',
# ' Bwd Packets/s',
# ' Idle Max',
# 'Fwd PSH Flags',
# ' Flow IAT Std',
# ' Idle Std',
# 'Flow Bytes/s',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' Flow Packets/s',
# ' Bwd Avg Packets/Bulk',
# ' Total Length of Bwd Packets',
# 'Bwd Avg Bulk Rate',
# ' Bwd IAT Min',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd IAT Mean',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Bwd IAT Std',
# 'FIN Flag Count',
# ' RST Flag Count',
# ' ACK Flag Count',
# ' Fwd Avg Bulk Rate',
# ' URG Flag Count',
# ' CWE Flag Count',
# ' ECE Flag Count',
# ' Down/Up Ratio',
# 'Fwd Avg Bytes/Bulk',
# ' Fwd Avg Packets/Bulk',
# ' Avg Fwd Segment Size',
]

Trial_3 =[
' Destination Port',
' Average Packet Size',
' Flow IAT Mean',
' Bwd Packet Length Min',
'Init_Win_bytes_forward',
' Avg Fwd Segment Size',
' Fwd IAT Mean',
' Fwd IAT Std',
' Avg Bwd Segment Size',
' Fwd IAT Max',
' min_seg_size_forward',
' Fwd Packet Length Mean',
' Fwd Packet Length Std',
'Subflow Fwd Packets',
'Active Mean',
' Active Max',
' Subflow Fwd Bytes',
' Flow IAT Max',
' Init_Win_bytes_backward',
' Fwd Packet Length Min',
# ' Bwd Header Length',
# ' Flow Duration',
# ' Fwd Packet Length Max',
# ' Subflow Bwd Packets',
# 'Bwd IAT Total',
# ' Total Backward Packets',
# ' Bwd Packet Length Std',
# ' Packet Length Std',
# ' Bwd Packet Length Mean',
# ' act_data_pkt_fwd',
# 'Total Length of Fwd Packets',
# 'Bwd Packet Length Max',
# 'Idle Mean',
# ' Idle Max',
# ' Max Packet Length',
# ' Fwd Header Length',
# ' Fwd IAT Min',
# ' Bwd IAT Mean',
# ' Down/Up Ratio',
# ' Packet Length Variance',
# ' Packet Length Mean',
# ' Total Fwd Packets',
# ' Bwd IAT Min',
# ' Subflow Bwd Bytes',
# ' Bwd IAT Max',
# ' Flow IAT Std',
# ' Total Length of Bwd Packets',
# ' Active Min',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Packets/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Active Std',
# ' Idle Std',
# ' Fwd Avg Packets/Bulk',
# ' Min Packet Length',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd URG Flags',
# 'Flow Bytes/s',
# ' Flow Packets/s',
# ' Flow IAT Min',
# 'Fwd IAT Total',
# ' Bwd IAT Std',
# 'Fwd PSH Flags',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# 'Fwd Packets/s',
# ' ECE Flag Count',
# ' Bwd Packets/s',
# 'FIN Flag Count',
# ' SYN Flag Count',
# ' RST Flag Count',
# ' PSH Flag Count',
# ' ACK Flag Count',
# ' URG Flag Count',
# ' CWE Flag Count',
# ' Idle Min',
]

Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)
print('---------------------------------------------------------------------------------')
print('DNN LIME CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')

Trial_1 = ['Bwd Avg Bulk Rate',
' PSH Flag Count',
'Active Mean',
'Bwd Packet Length Max',
' Idle Std',
' Init_Win_bytes_backward',
' Subflow Bwd Packets',
'Bwd IAT Total',
' Min Packet Length',
' Packet Length Variance',
' Packet Length Std',
' Fwd IAT Min',
' Idle Max',
' min_seg_size_forward',
'FIN Flag Count',
' Fwd IAT Std',
' Fwd URG Flags',
' Flow IAT Min',
' Idle Min',
' Fwd IAT Mean',
# ' Fwd IAT Max',
# ' Packet Length Mean',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' SYN Flag Count',
# ' Fwd Packet Length Std',
# ' Flow Packets/s',
# ' Fwd Packet Length Max',
# ' RST Flag Count',
# ' Max Packet Length',
# ' Active Min',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Bulk Rate',
# ' Fwd Header Length',
# ' act_data_pkt_fwd',
# ' Active Max',
# ' Total Length of Bwd Packets',
# 'Init_Win_bytes_forward',
# ' Bwd Packet Length Std',
# ' Fwd Header Length',
# ' Total Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Total Backward Packets',
# ' Fwd Packet Length Min',
# ' Fwd Packet Length Mean',
# 'Flow Bytes/s',
# ' URG Flag Count',
# 'Subflow Fwd Packets',
# ' Flow IAT Std',
# 'Idle Mean',
# ' ACK Flag Count',
# ' Bwd Packet Length Min',
# ' CWE Flag Count',
# ' Fwd Avg Packets/Bulk',
# 'Fwd IAT Total',
# ' Bwd Header Length',
# 'Fwd Packets/s',
# ' Flow IAT Max',
# ' Bwd URG Flags',
# ' Flow IAT Mean',
# ' Bwd IAT Max',
# ' Destination Port',
# ' Bwd PSH Flags',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Packets/Bulk',
# ' Average Packet Size',
# 'Fwd PSH Flags',
# ' Bwd IAT Mean',
# ' Bwd IAT Min',
# ' ECE Flag Count',
# ' Flow Duration',
# ' Down/Up Ratio',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' Bwd Avg Bytes/Bulk',
]

Trial_2 = ['Bwd Avg Bulk Rate',
' PSH Flag Count',
'Active Mean',
'Bwd Packet Length Max',
' Idle Std',
' Init_Win_bytes_backward',
' Subflow Bwd Packets',
'Bwd IAT Total',
' Min Packet Length',
' Packet Length Variance',
' Packet Length Std',
' Fwd IAT Min',
' Idle Max',
' min_seg_size_forward',
'FIN Flag Count',
' Fwd IAT Std',
' Fwd URG Flags',
' Flow IAT Min',
' Idle Min',
' Fwd IAT Mean',
# ' Fwd IAT Max',
# ' Packet Length Mean',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' SYN Flag Count',
# ' Fwd Packet Length Std',
# ' Flow Packets/s',
# ' Fwd Packet Length Max',
# ' RST Flag Count',
# ' Max Packet Length',
# ' Active Min',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Bulk Rate',
# ' Fwd Header Length',
# ' act_data_pkt_fwd',
# ' Active Max',
# ' Total Length of Bwd Packets',
# 'Init_Win_bytes_forward',
# ' Fwd Header Length',
# ' Bwd Packet Length Std',
# ' Total Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Total Backward Packets',
# ' Fwd Packet Length Min',
# ' Fwd Packet Length Mean',
# 'Flow Bytes/s',
# ' URG Flag Count',
# 'Subflow Fwd Packets',
# ' Flow IAT Std',
# 'Idle Mean',
# ' ACK Flag Count',
# ' Bwd Packet Length Min',
# ' CWE Flag Count',
# ' Fwd Avg Packets/Bulk',
# 'Fwd IAT Total',
# ' Bwd Header Length',
# 'Fwd Packets/s',
# ' Flow IAT Max',
# ' Bwd URG Flags',
# ' Flow IAT Mean',
# ' Bwd IAT Max',
# ' Destination Port',
# ' Bwd PSH Flags',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Packets/Bulk',
# 'Fwd PSH Flags',
# ' Average Packet Size',
# ' Bwd IAT Mean',
# ' Bwd IAT Min',
# ' ECE Flag Count',
# ' Flow Duration',
# ' Down/Up Ratio',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' Bwd Avg Bytes/Bulk',
]

Trial_3 = ['Bwd Avg Bulk Rate',
' PSH Flag Count',
'Active Mean',
'Bwd Packet Length Max',
' Idle Std',
' Init_Win_bytes_backward',
' Subflow Bwd Packets',
'Bwd IAT Total',
' Min Packet Length',
' Packet Length Variance',
' Packet Length Std',
' Fwd IAT Min',
' Idle Max',
' min_seg_size_forward',
'FIN Flag Count',
' Fwd IAT Std',
' Fwd URG Flags',
' Flow IAT Min',
' Idle Min',
' Fwd IAT Mean',
# ' Fwd IAT Max',
# ' Packet Length Mean',
# ' Subflow Bwd Bytes',
# ' SYN Flag Count',
# ' Active Std',
# ' Fwd Packet Length Std',
# ' Flow Packets/s',
# ' Fwd Packet Length Max',
# ' RST Flag Count',
# ' Max Packet Length',
# ' Active Min',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Bulk Rate',
# ' Fwd Header Length',
# ' act_data_pkt_fwd',
# ' Total Length of Bwd Packets',
# ' Active Max',
# ' Fwd Packet Length Min',
# ' Bwd Packet Length Std',
# 'Init_Win_bytes_forward',
# ' Fwd Header Length',
# ' Total Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Total Backward Packets',
# ' Fwd Packet Length Mean',
# 'Flow Bytes/s',
# ' URG Flag Count',
# ' ACK Flag Count',
# 'Subflow Fwd Packets',
# 'Idle Mean',
# ' Flow IAT Std',
# ' CWE Flag Count',
# ' Bwd Packet Length Min',
# 'Fwd IAT Total',
# ' Fwd Avg Packets/Bulk',
# 'Fwd Packets/s',
# ' Bwd Header Length',
# ' Flow IAT Max',
# ' Bwd URG Flags',
# ' Flow IAT Mean',
# ' Bwd IAT Max',
# ' Destination Port',
# ' Bwd PSH Flags',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Packets/Bulk',
# ' Average Packet Size',
# 'Fwd PSH Flags',
# ' Bwd IAT Mean',
# ' ECE Flag Count',
# ' Bwd IAT Min',
# ' Flow Duration',
# ' Down/Up Ratio',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' Bwd Avg Bytes/Bulk',
]

Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)
###########################################################################################################################################################################################################################################################################################################################
print('---------------------------------------------------------------------------------')
print('DNN SHAP CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')


Trial_1 =[
' PSH Flag Count',
' ACK Flag Count',
' Flow Duration',
'Bwd IAT Total',
'Fwd IAT Total',
' Destination Port',
' Init_Win_bytes_backward',
' Idle Max',
' Bwd IAT Max',
'Fwd PSH Flags',
'Idle Mean',
' Flow IAT Max',
'Init_Win_bytes_forward',
' Fwd IAT Std',
' URG Flag Count',
' Average Packet Size',
' Subflow Fwd Bytes',
' SYN Flag Count',
' Avg Bwd Segment Size',
'Total Length of Fwd Packets',
# ' min_seg_size_forward',
# ' Idle Std',
# ' Packet Length Variance',
# ' Bwd IAT Std',
# 'Bwd Packet Length Max',
# ' Bwd Packet Length Mean',
# ' Active Std',
# ' Idle Min',
# 'Active Mean',
# ' Avg Fwd Segment Size',
# ' Fwd IAT Max',
# 'Fwd Packets/s',
# ' Fwd Packet Length Mean',
# ' Flow IAT Std',
# ' Packet Length Std',
# ' Fwd IAT Mean',
# ' Active Max',
# ' Packet Length Mean',
# ' Bwd Packet Length Std',
# ' Flow IAT Mean',
# ' Bwd Packet Length Min',
# ' Fwd Packet Length Min',
# ' Min Packet Length',
# ' Down/Up Ratio',
# ' Active Min',
# ' Bwd IAT Mean',
# ' Bwd Packets/s',
# ' Fwd Packet Length Max',
# ' Max Packet Length',
# 'FIN Flag Count',
# ' Fwd Packet Length Std',
# ' act_data_pkt_fwd',
# ' Fwd IAT Min',
# ' Total Fwd Packets',
# 'Subflow Fwd Packets',
# ' Fwd Header Length',
# ' Bwd Header Length',
# ' Subflow Bwd Packets',
# ' Total Backward Packets',
# ' Bwd IAT Min',
# ' Flow IAT Min',
# ' Subflow Bwd Bytes',
# ' Total Length of Bwd Packets',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Bwd PSH Flags',
# ' RST Flag Count',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Packets/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Fwd Avg Packets/Bulk',
# 'Fwd Avg Bytes/Bulk',
# ' ECE Flag Count',
# ' CWE Flag Count',
# ' Flow Packets/s',
# 'Flow Bytes/s',
]

Trial_2=[
' URG Flag Count',
' ACK Flag Count',
'Init_Win_bytes_forward',
' SYN Flag Count',
'Bwd IAT Total',
' Bwd IAT Max',
' min_seg_size_forward',
' Flow IAT Max',
' Flow Duration',
' Init_Win_bytes_backward',
'Bwd Packet Length Max',
' Fwd IAT Max',
' Idle Max',
' Subflow Fwd Bytes',
' Idle Std',
' Avg Bwd Segment Size',
'Total Length of Fwd Packets',
' PSH Flag Count',
' Bwd IAT Std',
' Bwd Packet Length Std',
# 'Fwd IAT Total',
# 'FIN Flag Count',
# 'Fwd Packets/s',
# ' Fwd IAT Std',
# ' Packet Length Std',
# ' Bwd Packet Length Mean',
# 'Fwd PSH Flags',
# ' Active Std',
# ' Average Packet Size',
# 'Idle Mean',
# ' Fwd Packet Length Max',
# ' Down/Up Ratio',
# ' Bwd IAT Mean',
# ' Destination Port',
# ' Fwd IAT Mean',
# ' Flow IAT Std',
# ' Packet Length Mean',
# ' Flow IAT Mean',
# ' Packet Length Variance',
# ' Idle Min',
# ' Active Max',
# ' Avg Fwd Segment Size',
# ' Fwd Packet Length Std',
# ' Bwd Packets/s',
# 'Active Mean',
# ' Fwd Packet Length Mean',
# ' Active Min',
# ' Min Packet Length',
# ' Fwd Packet Length Min',
# ' Fwd IAT Min',
# ' Bwd Packet Length Min',
# ' act_data_pkt_fwd',
# 'Subflow Fwd Packets',
# ' Total Fwd Packets',
# ' Bwd Header Length',
# ' Max Packet Length',
# ' Total Backward Packets',
# ' Subflow Bwd Packets',
# ' Fwd Header Length',
# ' Bwd IAT Min',
# ' Flow IAT Min',
# ' Subflow Bwd Bytes',
# ' Total Length of Bwd Packets',
# ' Fwd Avg Packets/Bulk',
# ' Bwd URG Flags',
# ' RST Flag Count',
# ' Fwd URG Flags',
# ' Bwd PSH Flags',
# ' ECE Flag Count',
# ' CWE Flag Count',
# ' Fwd Avg Bulk Rate',
# 'Flow Bytes/s',
# ' Flow Packets/s',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Packets/Bulk',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Bytes/Bulk',
]

Trial_3 =[
' ACK Flag Count',
'Init_Win_bytes_forward',
' URG Flag Count',
' min_seg_size_forward',
' Flow IAT Max',
'Fwd IAT Total',
'Fwd PSH Flags',
' SYN Flag Count',
' PSH Flag Count',
' Destination Port',
' Init_Win_bytes_backward',
' Flow Duration',
' Bwd Packet Length Mean',
' Flow IAT Std',
' Fwd IAT Std',
' Bwd Packet Length Std',
' Max Packet Length',
' Subflow Fwd Bytes',
'Bwd IAT Total',
' Idle Min',
# 'Total Length of Fwd Packets',
# 'Idle Mean',
# ' Packet Length Mean',
# ' Fwd IAT Max',
# ' Packet Length Variance',
# ' Bwd IAT Max',
# ' Down/Up Ratio',
# 'FIN Flag Count',
# ' Idle Max',
# ' Average Packet Size',
# ' Fwd Packet Length Std',
# ' Fwd Packet Length Mean',
# 'Fwd Packets/s',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' Bwd IAT Std',
# 'Bwd Packet Length Max',
# ' Packet Length Std',
# ' Fwd IAT Mean',
# ' Active Std',
# ' Bwd Packets/s',
# ' Flow IAT Mean',
# 'Active Mean',
# ' Idle Std',
# ' Bwd IAT Mean',
# ' Active Min',
# ' Fwd Packet Length Max',
# ' Total Fwd Packets',
# ' Active Max',
# ' act_data_pkt_fwd',
# ' Bwd IAT Min',
# ' Fwd IAT Min',
# 'Subflow Fwd Packets',
# ' Total Backward Packets',
# ' Bwd Header Length',
# ' Min Packet Length',
# ' Bwd Packet Length Min',
# ' Fwd Packet Length Min',
# ' Flow IAT Min',
# ' Subflow Bwd Packets',
# ' Fwd Header Length',
# ' Total Length of Bwd Packets',
# ' Subflow Bwd Bytes',
# ' Flow Packets/s',
# 'Flow Bytes/s',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Fwd Avg Packets/Bulk',
# ' RST Flag Count',
# ' Fwd Avg Bulk Rate',
# ' ECE Flag Count',
# 'Fwd Avg Bytes/Bulk',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Packets/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' CWE Flag Count',
]
Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)

###########################################################################################################################################################################################################################################################################################################################
print('---------------------------------------------------------------------------------')
print('RF LIME CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')
Trial_1 = [
    'Bwd Avg Bulk Rate',
'Bwd IAT Total',
'Active Mean',
' Bwd Packet Length Mean',
'Bwd Packet Length Max',
' Min Packet Length',
'FIN Flag Count',
' Bwd PSH Flags',
' min_seg_size_forward',
' Init_Win_bytes_backward',
' Packet Length Std',
' Fwd IAT Max',
' Idle Std',
'Subflow Fwd Packets',
' Packet Length Variance',
'Init_Win_bytes_forward',
' Fwd URG Flags',
'Flow Bytes/s',
' Fwd IAT Min',
' SYN Flag Count',
# ' Bwd Packets/s',
# ' Bwd IAT Std',
# ' Packet Length Mean',
# ' Idle Min',
# ' Fwd Packet Length Mean',
# ' Max Packet Length',
# ' Fwd IAT Std',
# ' PSH Flag Count',
# ' Subflow Bwd Bytes',
# ' Bwd IAT Mean',
# 'Idle Mean',
# ' Idle Max',
# ' Fwd Packet Length Min',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Bwd Packet Length Std',
# ' Bwd URG Flags',
# ' Fwd IAT Mean',
# ' Bwd Packet Length Min',
# ' Fwd Packet Length Max',
# ' Fwd Packet Length Std',
# ' RST Flag Count',
# ' Total Backward Packets',
# ' Bwd Avg Packets/Bulk',
# ' Flow IAT Min',
# ' Subflow Bwd Packets',
# ' Total Length of Bwd Packets',
# ' Fwd Header Length',
# ' Fwd Avg Bulk Rate',
# ' Active Std',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Min',
# ' Fwd Header Length',
# ' Flow Packets/s',
# ' Down/Up Ratio',
# ' Fwd Avg Packets/Bulk',
# ' act_data_pkt_fwd',
# ' URG Flag Count',
# ' Bwd Header Length',
# ' Bwd IAT Max',
# 'Fwd Avg Bytes/Bulk',
# ' Flow IAT Std',
# ' Destination Port',
# ' Active Min',
# 'Fwd IAT Total',
# ' Flow IAT Mean',
# ' Active Max',
# ' Flow IAT Max',
# ' Avg Fwd Segment Size',
# 'Fwd PSH Flags',
# ' ACK Flag Count',
# ' ECE Flag Count',
# ' Average Packet Size',
# ' Flow Duration',
# 'Fwd Packets/s',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]
Trial_2 = [
    'Bwd Avg Bulk Rate',
'Bwd IAT Total',
'Active Mean',
' Bwd Packet Length Mean',
'Bwd Packet Length Max',
' Min Packet Length',
'FIN Flag Count',
' Bwd PSH Flags',
' min_seg_size_forward',
' Init_Win_bytes_backward',
' Packet Length Std',
' Fwd IAT Max',
' Idle Std',
'Subflow Fwd Packets',
' Packet Length Variance',
'Init_Win_bytes_forward',
' Fwd URG Flags',
'Flow Bytes/s',
' Fwd IAT Min',
' SYN Flag Count',
# ' Bwd Packets/s',
# ' Bwd IAT Std',
# ' Packet Length Mean',
# ' Idle Min',
# ' Fwd Packet Length Mean',
# ' Max Packet Length',
# ' Fwd IAT Std',
# ' PSH Flag Count',
# ' Subflow Bwd Bytes',
# ' Bwd IAT Mean',
# 'Idle Mean',
# ' Idle Max',
# ' Fwd Packet Length Min',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Bwd Packet Length Std',
# ' Bwd URG Flags',
# ' Fwd IAT Mean',
# ' Bwd Packet Length Min',
# ' Fwd Packet Length Max',
# ' Fwd Packet Length Std',
# ' RST Flag Count',
# ' Total Backward Packets',
# ' Bwd Avg Packets/Bulk',
# ' Flow IAT Min',
# ' Subflow Bwd Packets',
# ' Total Length of Bwd Packets',
# ' Fwd Header Length',
# ' Fwd Avg Bulk Rate',
# ' Active Std',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Min',
# ' Fwd Header Length',
# ' Flow Packets/s',
# ' Down/Up Ratio',
# ' Fwd Avg Packets/Bulk',
# ' act_data_pkt_fwd',
# ' URG Flag Count',
# ' Bwd Header Length',
# ' Bwd IAT Max',
# 'Fwd Avg Bytes/Bulk',
# ' Flow IAT Std',
# ' Destination Port',
# ' Active Min',
# 'Fwd IAT Total',
# ' Flow IAT Mean',
# ' Active Max',
# ' Flow IAT Max',
# ' Avg Fwd Segment Size',
# 'Fwd PSH Flags',
# ' ACK Flag Count',
# ' ECE Flag Count',
# ' Average Packet Size',
# ' Flow Duration',
# 'Fwd Packets/s',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]
Trial_3 = [
'Bwd Avg Bulk Rate',
'Bwd IAT Total',
'Active Mean',
' Bwd Packet Length Mean',
'Bwd Packet Length Max',
' Min Packet Length',
'FIN Flag Count',
' Bwd PSH Flags',
' min_seg_size_forward',
' Init_Win_bytes_backward',
' Packet Length Std',
' Fwd IAT Max',
' Idle Std',
'Subflow Fwd Packets',
' Packet Length Variance',
'Init_Win_bytes_forward',
' Fwd URG Flags',
'Flow Bytes/s',
' Fwd IAT Min',
' SYN Flag Count',
# ' Bwd Packets/s',
# ' Bwd IAT Std',
# ' Packet Length Mean',
# ' Idle Min',
# ' Fwd Packet Length Mean',
# ' Max Packet Length',
# ' Fwd IAT Std',
# ' PSH Flag Count',
# ' Subflow Bwd Bytes',
# ' Bwd IAT Mean',
# 'Idle Mean',
# ' Idle Max',
# ' Fwd Packet Length Min',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Bwd Packet Length Std',
# ' Bwd URG Flags',
# ' Fwd IAT Mean',
# ' Bwd Packet Length Min',
# ' Fwd Packet Length Max',
# ' Fwd Packet Length Std',
# ' RST Flag Count',
# ' Total Backward Packets',
# ' Bwd Avg Packets/Bulk',
# ' Flow IAT Min',
# ' Subflow Bwd Packets',
# ' Total Length of Bwd Packets',
# ' Fwd Header Length',
# ' Fwd Avg Bulk Rate',
# ' Active Std',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Min',
# ' Fwd Header Length',
# ' Flow Packets/s',
# ' Down/Up Ratio',
# ' Fwd Avg Packets/Bulk',
# ' act_data_pkt_fwd',
# ' URG Flag Count',
# ' Bwd Header Length',
# ' Bwd IAT Max',
# 'Fwd Avg Bytes/Bulk',
# ' Flow IAT Std',
# ' Destination Port',
# ' Active Min',
# 'Fwd IAT Total',
# ' Flow IAT Mean',
# ' Active Max',
# ' Flow IAT Max',
# ' Avg Fwd Segment Size',
# 'Fwd PSH Flags',
# ' ACK Flag Count',
# ' ECE Flag Count',
# ' Average Packet Size',
# ' Flow Duration',
# 'Fwd Packets/s',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]
Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)

###########################################################################################################################################################################################################################################################################################################################
print('---------------------------------------------------------------------------------')
print('LGBM SHAP CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')

Trial_1 = [
' Destination Port',
' Init_Win_bytes_backward',
' Bwd IAT Max',
' min_seg_size_forward',
'Init_Win_bytes_forward',
' Bwd Packets/s',
' PSH Flag Count',
' Bwd Packet Length Std',
' Fwd IAT Min',
' Flow IAT Min',
'Fwd Packets/s',
' Flow IAT Mean',
' Fwd Header Length',
' Flow IAT Max',
' Bwd Packet Length Mean',
' Bwd IAT Std',
' Total Fwd Packets',
' Bwd Packet Length Min',
' Flow Duration',
' Packet Length Mean'
# ' Fwd Packet Length Max',
# ' URG Flag Count',
# 'Total Length of Fwd Packets',
# ' Average Packet Size',
# ' Bwd IAT Min',
# ' Fwd IAT Std',
# ' Idle Max',
# ' Total Length of Bwd Packets',
# ' Max Packet Length',
# ' ACK Flag Count',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Packet Length Std',
# 'Bwd Packet Length Max',
# ' Flow IAT Std',
# 'Fwd IAT Total',
# ' Bwd Header Length',
# ' act_data_pkt_fwd',
# ' Fwd IAT Max',
# ' Total Backward Packets',
# 'Idle Mean',
# 'Bwd IAT Total',
# 'FIN Flag Count',
# ' Fwd Packet Length Std',
# ' Active Max',
# ' Down/Up Ratio',
# ' Idle Min',
# ' Bwd IAT Mean',
# ' Min Packet Length',
# ' Active Min',
# ' SYN Flag Count',
# ' Packet Length Variance',
# ' Idle Std',
# ' Fwd Packet Length Min',
# ' Active Std',
# 'Active Mean',
# 'Fwd PSH Flags',
# ' Subflow Bwd Packets',
# 'Flow Bytes/s',
# ' Flow Packets/s',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Subflow Bwd Bytes',
# ' RST Flag Count',
# 'Subflow Fwd Packets',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Packets/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Fwd Avg Packets/Bulk',
# 'Fwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' Bwd URG Flags',
# ' ECE Flag Count',
# ' CWE Flag Count',
# ' Subflow Fwd Bytes',
]
Trial_2 = [
' Destination Port',
' Init_Win_bytes_backward',
'Bwd IAT Total',
' min_seg_size_forward',
' Bwd Packets/s',
'Init_Win_bytes_forward',
' PSH Flag Count',
' Flow Duration',
' Fwd IAT Min',
' Bwd Packet Length Std',
' Total Fwd Packets',
' Flow IAT Min',
' Bwd Packet Length Min',
' Fwd Header Length',
' Bwd Packet Length Mean',
' Fwd Packet Length Max',
' Flow IAT Max',
' Bwd IAT Min',
'Fwd Packets/s',
' Fwd Packet Length Mean'
# ' Fwd IAT Std',
# ' Flow IAT Std',
# ' Packet Length Mean',
# ' Total Length of Bwd Packets',
# 'Bwd Packet Length Max',
# 'Total Length of Fwd Packets',
# ' Flow IAT Mean',
# ' Idle Max',
# ' Bwd IAT Std',
# ' Packet Length Std',
# ' Average Packet Size',
# 'Idle Mean',
# ' Total Backward Packets',
# ' Max Packet Length',
# ' Bwd IAT Max',
# 'Fwd IAT Total',
# ' act_data_pkt_fwd',
# ' Fwd IAT Max',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Std',
# ' URG Flag Count',
# ' ACK Flag Count',
# ' Idle Min',
# ' Active Min',
# 'FIN Flag Count',
# ' Down/Up Ratio',
# ' Bwd Header Length',
# ' SYN Flag Count',
# ' Packet Length Variance',
# ' Bwd IAT Mean',
# ' Min Packet Length',
# ' Active Max',
# 'Active Mean',
# ' Idle Std',
# ' Active Std',
# 'Fwd PSH Flags',
# ' Fwd Packet Length Min',
# ' ECE Flag Count',
# ' Fwd URG Flags',
# 'Flow Bytes/s',
# ' RST Flag Count',
# ' Flow Packets/s',
# ' Bwd URG Flags',
# ' Bwd PSH Flags',
# ' Subflow Bwd Bytes',
# ' Subflow Bwd Packets',
# ' Subflow Fwd Bytes',
# 'Subflow Fwd Packets',
# ' CWE Flag Count',
# ' Bwd Avg Packets/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Fwd Avg Packets/Bulk',
# 'Fwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# 'Bwd Avg Bulk Rate'
]

Trial_3 = [
' Destination Port',
' Init_Win_bytes_backward',
' act_data_pkt_fwd',
'Init_Win_bytes_forward',
' min_seg_size_forward',
' Flow IAT Min',
' Total Fwd Packets',
' Bwd Packets/s',
' PSH Flag Count',
' Bwd Packet Length Std',
' Packet Length Mean',
' Bwd IAT Min',
' Flow Duration',
' Fwd IAT Min',
'Bwd Packet Length Max',
'Total Length of Fwd Packets',
' Bwd Packet Length Min',
' Packet Length Std',
' Fwd Header Length',
' Fwd IAT Std'
# ' Max Packet Length',
# ' Average Packet Size',
# ' Flow IAT Max',
# ' Bwd Header Length',
# ' Bwd Packet Length Mean',
# ' Fwd Packet Length Min',
# ' Min Packet Length',
# ' URG Flag Count',
# ' Total Backward Packets',
# 'Fwd Packets/s',
# ' Idle Min',
# ' Fwd IAT Mean',
# 'Bwd IAT Total',
# ' Fwd Packet Length Mean',
# ' Total Length of Bwd Packets',
# ' Fwd Packet Length Max',
# ' Bwd IAT Std',
# ' Flow IAT Std',
# ' Fwd Packet Length Std',
# 'Fwd IAT Total',
# ' Active Min',
# ' Fwd IAT Max',
# ' Flow IAT Mean',
# ' Idle Max',
# ' Down/Up Ratio',
# 'FIN Flag Count',
# ' Packet Length Variance',
# ' Bwd IAT Max',
# ' ACK Flag Count',
# ' Bwd IAT Mean',
# ' SYN Flag Count',
# ' Active Std',
# 'Active Mean',
# 'Fwd PSH Flags',
# 'Idle Mean',
# ' Active Max',
# ' Idle Std',
# ' Subflow Fwd Bytes',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Subflow Bwd Bytes',
# ' Subflow Bwd Packets',
# ' Bwd Avg Packets/Bulk',
# 'Subflow Fwd Packets',
# 'Bwd Avg Bulk Rate',
# ' Bwd Avg Bytes/Bulk',
# ' Flow Packets/s',
# ' Fwd Avg Packets/Bulk',
# 'Fwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
# ' ECE Flag Count',
# ' CWE Flag Count',
# ' Bwd URG Flags',
# 'Flow Bytes/s',
# ' RST Flag Count',
# ' Fwd Avg Bulk Rate',
]


Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)

###########################################################################################################################################################################################################################################################################################################################
print('---------------------------------------------------------------------------------')
print('LGBM LIME CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')

Trial_1 = [

' Bwd Packet Length Min',
' Bwd PSH Flags',
' Bwd IAT Min',
' CWE Flag Count',
' Bwd Packets/s',
' Bwd Header Length',
' Bwd Packet Length Mean',
' Packet Length Std',
' Packet Length Mean',
' Subflow Fwd Bytes',
' Subflow Bwd Bytes',
' Fwd Packet Length Min',
' Subflow Bwd Packets',
' Fwd IAT Max',
' Min Packet Length',
'Init_Win_bytes_forward',
' Total Length of Bwd Packets',
' URG Flag Count',
'Active Mean',
' Init_Win_bytes_backward',
# ' RST Flag Count',
# ' Bwd IAT Max',
# ' Fwd IAT Mean',
# ' Packet Length Variance',
# ' Fwd URG Flags',
# ' ACK Flag Count',
# ' SYN Flag Count',
# ' Max Packet Length',
# ' Idle Std',
# 'FIN Flag Count',
# ' min_seg_size_forward',
# 'Idle Mean',
# ' Bwd IAT Mean',
# 'Fwd IAT Total',
# ' Idle Min',
# ' Fwd Header Length',
# ' Fwd Packet Length Std',
# ' PSH Flag Count',
# ' Active Std',
# ' Idle Max',
# ' act_data_pkt_fwd',
# 'Subflow Fwd Packets',
# ' Flow Packets/s',
# ' Bwd URG Flags',
# ' Fwd Packet Length Mean',
# ' Active Min',
# ' Total Backward Packets',
# ' Total Fwd Packets',
# ' Fwd IAT Std',
# 'Bwd Packet Length Max',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Packet Length Max',
# ' Fwd Header Length',
# ' Destination Port',
# ' Flow IAT Min',
# ' Flow IAT Std',
# ' Active Max',
# ' Fwd IAT Min',
# ' Flow IAT Mean',
# 'Flow Bytes/s',
# 'Bwd Avg Bulk Rate',
# ' Bwd Packet Length Std',
# ' Flow IAT Max',
# ' Fwd Avg Bulk Rate',
# 'Bwd IAT Total',
# ' Bwd Avg Packets/Bulk',
# 'Fwd PSH Flags',
# ' Down/Up Ratio',
# ' Flow Duration',
# ' ECE Flag Count',
# ' Avg Fwd Segment Size',
# 'Fwd Packets/s',
# ' Average Packet Size',
# ' Bwd IAT Std',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]

Trial_2 = [

    ' Bwd Packet Length Min',
' Bwd PSH Flags',
' Bwd IAT Min',
' CWE Flag Count',
' Bwd Packets/s',
' Bwd Header Length',
' Bwd Packet Length Mean',
' Packet Length Std',
' Packet Length Mean',
' Subflow Fwd Bytes',
' Subflow Bwd Bytes',
' Fwd Packet Length Min',
' Subflow Bwd Packets',
' Fwd IAT Max',
' Min Packet Length',
'Init_Win_bytes_forward',
' Total Length of Bwd Packets',
' URG Flag Count',
'Active Mean',
' Init_Win_bytes_backward',
# ' RST Flag Count',
# ' Bwd IAT Max',
# ' Fwd IAT Mean',
# ' Packet Length Variance',
# ' Fwd URG Flags',
# ' ACK Flag Count',
# ' SYN Flag Count',
# ' Max Packet Length',
# ' Idle Std',
# 'FIN Flag Count',
# ' min_seg_size_forward',
# 'Idle Mean',
# ' Bwd IAT Mean',
# 'Fwd IAT Total',
# ' Idle Min',
# ' Fwd Header Length',
# ' Fwd Packet Length Std',
# ' PSH Flag Count',
# ' Active Std',
# ' Idle Max',
# ' act_data_pkt_fwd',
# 'Subflow Fwd Packets',
# ' Flow Packets/s',
# ' Bwd URG Flags',
# ' Fwd Packet Length Mean',
# ' Active Min',
# ' Total Backward Packets',
# ' Total Fwd Packets',
# ' Fwd IAT Std',
# 'Bwd Packet Length Max',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Packet Length Max',
# ' Fwd Header Length',
# ' Destination Port',
# ' Flow IAT Min',
# ' Flow IAT Std',
# ' Active Max',
# ' Fwd IAT Min',
# ' Flow IAT Mean',
# 'Flow Bytes/s',
# 'Bwd Avg Bulk Rate',
# ' Bwd Packet Length Std',
# ' Flow IAT Max',
# ' Fwd Avg Bulk Rate',
# 'Bwd IAT Total',
# ' Bwd Avg Packets/Bulk',
# 'Fwd PSH Flags',
# ' Down/Up Ratio',
# ' Flow Duration',
# ' ECE Flag Count',
# ' Avg Fwd Segment Size',
# 'Fwd Packets/s',
# ' Average Packet Size',
# ' Bwd IAT Std',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]

Trial_3 = [
    ' Bwd Packet Length Min',
' Bwd PSH Flags',
' Bwd IAT Min',
' CWE Flag Count',
' Bwd Packets/s',
' Bwd Header Length',
' Bwd Packet Length Mean',
' Packet Length Std',
' Packet Length Mean',
' Subflow Fwd Bytes',
' Subflow Bwd Bytes',
' Fwd Packet Length Min',
' Subflow Bwd Packets',
' Fwd IAT Max',
' Min Packet Length',
'Init_Win_bytes_forward',
' Total Length of Bwd Packets',
' URG Flag Count',
'Active Mean',
' Init_Win_bytes_backward',
# ' RST Flag Count',
# ' Bwd IAT Max',
# ' Fwd IAT Mean',
# ' Packet Length Variance',
# ' Fwd URG Flags',
# ' ACK Flag Count',
# ' SYN Flag Count',
# ' Max Packet Length',
# ' Idle Std',
# 'FIN Flag Count',
# ' min_seg_size_forward',
# 'Idle Mean',
# ' Bwd IAT Mean',
# 'Fwd IAT Total',
# ' Idle Min',
# ' Fwd Header Length',
# ' Fwd Packet Length Std',
# ' PSH Flag Count',
# ' Active Std',
# ' Idle Max',
# ' act_data_pkt_fwd',
# 'Subflow Fwd Packets',
# ' Flow Packets/s',
# ' Bwd URG Flags',
# ' Fwd Packet Length Mean',
# ' Active Min',
# ' Total Backward Packets',
# ' Total Fwd Packets',
# ' Fwd IAT Std',
# 'Bwd Packet Length Max',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Packet Length Max',
# ' Fwd Header Length',
# ' Destination Port',
# ' Flow IAT Min',
# ' Flow IAT Std',
# ' Active Max',
# ' Fwd IAT Min',
# ' Flow IAT Mean',
# 'Flow Bytes/s',
# 'Bwd Avg Bulk Rate',
# ' Bwd Packet Length Std',
# ' Flow IAT Max',
# ' Fwd Avg Bulk Rate',
# 'Bwd IAT Total',
# ' Bwd Avg Packets/Bulk',
# 'Fwd PSH Flags',
# ' Down/Up Ratio',
# ' Flow Duration',
# ' ECE Flag Count',
# ' Avg Fwd Segment Size',
# 'Fwd Packets/s',
# ' Average Packet Size',
# ' Bwd IAT Std',
# 'Fwd Avg Bytes/Bulk',
# ' Bwd Avg Bytes/Bulk',
# ' Avg Bwd Segment Size',
]

Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)

###########################################################################################################################################################################################################################################################################################################################
print('---------------------------------------------------------------------------------')
print('SVM SHAP CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')
Trial_1 = [
    
' PSH Flag Count',
' ACK Flag Count',
' min_seg_size_forward',
'Init_Win_bytes_forward',
' Init_Win_bytes_backward',
' Destination Port',
' URG Flag Count',
'Bwd IAT Total',
' Flow Duration',
' Fwd IAT Max',
' Flow IAT Max',
' Bwd IAT Max',
'Fwd IAT Total',
' Idle Max',
'FIN Flag Count',
' Packet Length Std',
' Packet Length Variance',
'Fwd PSH Flags',
' SYN Flag Count',
' Bwd Packet Length Std',
# 'Idle Mean',
# ' Packet Length Mean',
# ' Fwd IAT Std',
# ' Idle Min',
# ' Bwd Packet Length Mean',
# ' Avg Bwd Segment Size',
# ' Average Packet Size',
# ' Fwd Packet Length Std',
# 'Bwd Packet Length Max',
# ' Flow IAT Std',
# ' Max Packet Length',
# 'Total Length of Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# 'Fwd Packets/s',
# ' Avg Fwd Segment Size',
# ' Idle Std',
# ' Bwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Max',
# 'Active Mean',
# ' Active Min',
# ' Flow IAT Mean',
# ' Active Max',
# ' Bwd IAT Min',
# ' Fwd Packet Length Min',
# ' Bwd Packet Length Min',
# ' Bwd Header Length',
# 'Subflow Fwd Packets',
# ' Total Backward Packets',
# ' act_data_pkt_fwd',
# ' Fwd IAT Min',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' Down/Up Ratio',
# ' Flow IAT Min',
# ' Min Packet Length',
# ' Total Length of Bwd Packets',
# ' Total Fwd Packets',
# ' Subflow Bwd Packets',
# ' Fwd Header Length',
# ' Bwd Avg Packets/Bulk',
# 'Flow Bytes/s',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Flow Packets/s',
# ' RST Flag Count',
# 'Bwd Avg Bulk Rate',
# ' CWE Flag Count',
# 'Fwd Avg Bytes/Bulk',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Bwd Avg Bytes/Bulk',
# ' ECE Flag Count',
]

Trial_2 = [

' PSH Flag Count',
' ACK Flag Count',
' min_seg_size_forward',
'Init_Win_bytes_forward',
' Init_Win_bytes_backward',
' Destination Port',
' URG Flag Count',
'Bwd IAT Total',
' Flow Duration',
' Fwd IAT Max',
' Flow IAT Max',
' Bwd IAT Max',
'Fwd IAT Total',
' Idle Max',
'FIN Flag Count',
' Packet Length Std',
' Packet Length Variance',
'Fwd PSH Flags',
' SYN Flag Count',
' Bwd Packet Length Std',
# 'Idle Mean',
# ' Packet Length Mean',
# ' Fwd IAT Std',
# ' Idle Min',
# ' Bwd Packet Length Mean',
# ' Avg Bwd Segment Size',
# ' Average Packet Size',
# ' Fwd Packet Length Std',
# 'Bwd Packet Length Max',
# ' Flow IAT Std',
# ' Max Packet Length',
# 'Total Length of Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# 'Fwd Packets/s',
# ' Avg Fwd Segment Size',
# ' Idle Std',
# ' Bwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Max',
# 'Active Mean',
# ' Active Min',
# ' Flow IAT Mean',
# ' Active Max',
# ' Bwd IAT Min',
# ' Fwd Packet Length Min',
# ' Bwd Packet Length Min',
# ' Bwd Header Length',
# 'Subflow Fwd Packets',
# ' Total Backward Packets',
# ' act_data_pkt_fwd',
# ' Fwd IAT Min',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' Down/Up Ratio',
# ' Flow IAT Min',
# ' Min Packet Length',
# ' Total Length of Bwd Packets',
# ' Total Fwd Packets',
# ' Subflow Bwd Packets',
# ' Fwd Header Length',
# ' Bwd Avg Packets/Bulk',
# 'Flow Bytes/s',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Flow Packets/s',
# ' RST Flag Count',
# 'Bwd Avg Bulk Rate',
# ' CWE Flag Count',
# 'Fwd Avg Bytes/Bulk',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Bwd Avg Bytes/Bulk',
# ' ECE Flag Count',
]

Trial_3 = [
    ' PSH Flag Count',
' ACK Flag Count',
' min_seg_size_forward',
'Init_Win_bytes_forward',
' Init_Win_bytes_backward',
' Destination Port',
' URG Flag Count',
'Bwd IAT Total',
' Flow Duration',
' Fwd IAT Max',
' Flow IAT Max',
' Bwd IAT Max',
'Fwd IAT Total',
' Idle Max',
'FIN Flag Count',
' Packet Length Std',
' Packet Length Variance',
'Fwd PSH Flags',
' SYN Flag Count',
' Bwd Packet Length Std',
# 'Idle Mean',
# ' Packet Length Mean',
# ' Fwd IAT Std',
# ' Idle Min',
# ' Bwd Packet Length Mean',
# ' Avg Bwd Segment Size',
# ' Average Packet Size',
# ' Fwd Packet Length Std',
# 'Bwd Packet Length Max',
# ' Flow IAT Std',
# ' Max Packet Length',
# 'Total Length of Fwd Packets',
# ' Subflow Fwd Bytes',
# ' Bwd IAT Std',
# ' Bwd Packets/s',
# 'Fwd Packets/s',
# ' Avg Fwd Segment Size',
# ' Idle Std',
# ' Bwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Max',
# 'Active Mean',
# ' Active Min',
# ' Flow IAT Mean',
# ' Active Max',
# ' Bwd IAT Min',
# ' Fwd Packet Length Min',
# ' Bwd Packet Length Min',
# ' Bwd Header Length',
# 'Subflow Fwd Packets',
# ' Total Backward Packets',
# ' act_data_pkt_fwd',
# ' Fwd IAT Min',
# ' Subflow Bwd Bytes',
# ' Active Std',
# ' Down/Up Ratio',
# ' Flow IAT Min',
# ' Min Packet Length',
# ' Total Length of Bwd Packets',
# ' Total Fwd Packets',
# ' Subflow Bwd Packets',
# ' Fwd Header Length',
# ' Bwd Avg Packets/Bulk',
# 'Flow Bytes/s',
# ' Bwd PSH Flags',
# ' Fwd URG Flags',
# ' Bwd URG Flags',
# ' Flow Packets/s',
# ' RST Flag Count',
# 'Bwd Avg Bulk Rate',
# ' CWE Flag Count',
# 'Fwd Avg Bytes/Bulk',
# ' Fwd Avg Packets/Bulk',
# ' Fwd Avg Bulk Rate',
# ' Bwd Avg Bytes/Bulk',
# ' ECE Flag Count',
]

Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)

print('---------------------------------------------------------------------------------')
print('SVM LIME CICIDS GLOBAL')
print('---------------------------------------------------------------------------------')


Trial_1 = [
' ACK Flag Count',
'Bwd IAT Total',
'Bwd Avg Bulk Rate',
' Packet Length Variance',
' Packet Length Std',
'Active Mean',
' Init_Win_bytes_backward',
'Bwd Packet Length Max',
' Idle Std',
' min_seg_size_forward',
' Fwd IAT Min',
'Idle Mean',
' Idle Max',
' Packet Length Mean',
' PSH Flag Count',
' Max Packet Length',
' Min Packet Length',
' Subflow Bwd Bytes',
'Fwd PSH Flags',
' Fwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Fwd URG Flags',
# 'Fwd Packets/s',
# ' Fwd IAT Max',
# ' Fwd Header Length',
# ' Fwd Header Length',
# ' Idle Min',
# ' SYN Flag Count',
# ' Fwd Packet Length Max',
# 'FIN Flag Count',
# ' Fwd Packet Length Min',
# 'Fwd IAT Total',
# ' Flow IAT Min',
# ' RST Flag Count',
# ' Flow IAT Std',
# ' Total Backward Packets',
# ' Fwd IAT Std',
# ' Fwd Packet Length Std',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Subflow Bwd Packets',
# 'Init_Win_bytes_forward',
# ' Bwd Packets/s',
# ' Bwd Header Length',
# ' Bwd Packet Length Min',
# 'Flow Bytes/s',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Packets/Bulk',
# ' Subflow Fwd Bytes',
# ' Flow Packets/s',
# ' Fwd Avg Bulk Rate',
# ' act_data_pkt_fwd',
# ' Bwd URG Flags',
# ' Bwd PSH Flags',
# 'Subflow Fwd Packets',
# ' Down/Up Ratio',
# ' Flow IAT Mean',
# ' Bwd Packet Length Std',
# 'Fwd Avg Bytes/Bulk',
# ' Active Std',
# ' Destination Port',
# ' URG Flag Count',
# ' Total Length of Bwd Packets',
# ' Bwd Avg Packets/Bulk',
# ' ECE Flag Count',
# ' Bwd Avg Bytes/Bulk',
# ' Flow IAT Max',
# ' Active Min',
# ' Bwd IAT Min',
# ' Bwd IAT Max',
# ' Flow Duration',
# ' Active Max',
# ' Bwd IAT Mean',
# ' Bwd IAT Std',
# ' Average Packet Size',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
]

Trial_2 = [
' ACK Flag Count',
'Bwd IAT Total',
'Bwd Avg Bulk Rate',
' Packet Length Variance',
' Packet Length Std',
'Active Mean',
' Init_Win_bytes_backward',
'Bwd Packet Length Max',
' Idle Std',
' min_seg_size_forward',
' Fwd IAT Min',
'Idle Mean',
' Idle Max',
' Packet Length Mean',
' PSH Flag Count',
' Max Packet Length',
' Min Packet Length',
' Subflow Bwd Bytes',
'Fwd PSH Flags',
# ' Fwd IAT Mean',
# ' Fwd Packet Length Mean',
# ' Fwd URG Flags',
# 'Fwd Packets/s',
# ' Fwd IAT Max',
# ' Fwd Header Length',
# ' Fwd Header Length',
# ' Idle Min',
# ' SYN Flag Count',
# ' Fwd Packet Length Max',
# 'FIN Flag Count',
# ' Fwd Packet Length Min',
# 'Fwd IAT Total',
# ' Flow IAT Min',
# ' RST Flag Count',
# ' Flow IAT Std',
# ' Total Backward Packets',
# ' Fwd IAT Std',
# ' Fwd Packet Length Std',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Subflow Bwd Packets',
# 'Init_Win_bytes_forward',
# ' Bwd Packets/s',
# ' Bwd Header Length',
# ' Bwd Packet Length Min',
# 'Flow Bytes/s',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Packets/Bulk',
# ' Subflow Fwd Bytes',
# ' Flow Packets/s',
# ' Fwd Avg Bulk Rate',
# ' act_data_pkt_fwd',
# ' Bwd URG Flags',
# ' Bwd PSH Flags',
# 'Subflow Fwd Packets',
# ' Down/Up Ratio',
# ' Flow IAT Mean',
# ' Bwd Packet Length Std',
# 'Fwd Avg Bytes/Bulk',
# ' Active Std',
# ' Destination Port',
# ' URG Flag Count',
# ' Total Length of Bwd Packets',
# ' Bwd Avg Packets/Bulk',
# ' ECE Flag Count',
# ' Bwd Avg Bytes/Bulk',
# ' Flow IAT Max',
# ' Active Min',
# ' Bwd IAT Min',
# ' Bwd IAT Max',
# ' Flow Duration',
# ' Active Max',
# ' Bwd IAT Mean',
# ' Bwd IAT Std',
# ' Average Packet Size',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
]
Trial_3 =[
' ACK Flag Count',
'Bwd IAT Total',
'Bwd Avg Bulk Rate',
' Packet Length Variance',
' Packet Length Std',
'Active Mean',
' Init_Win_bytes_backward',
'Bwd Packet Length Max',
' Idle Std',
' min_seg_size_forward',
' Fwd IAT Min',
'Idle Mean',
' Idle Max',
' Packet Length Mean',
' PSH Flag Count',
' Max Packet Length',
' Min Packet Length',
' Subflow Bwd Bytes',
'Fwd PSH Flags',
' Fwd IAT Mean',
' Fwd Packet Length Mean',
# ' Fwd URG Flags',
# 'Fwd Packets/s',
# ' Fwd IAT Max',
# ' Fwd Header Length',
# ' Fwd Header Length',
# ' Idle Min',
# ' SYN Flag Count',
# ' Fwd Packet Length Max',
# 'FIN Flag Count',
# ' Fwd Packet Length Min',
# 'Fwd IAT Total',
# ' Flow IAT Min',
# ' RST Flag Count',
# ' Flow IAT Std',
# ' Total Backward Packets',
# ' Fwd IAT Std',
# ' Fwd Packet Length Std',
# ' Total Fwd Packets',
# ' CWE Flag Count',
# ' Subflow Bwd Packets',
# 'Init_Win_bytes_forward',
# ' Bwd Packets/s',
# ' Bwd Header Length',
# ' Bwd Packet Length Min',
# 'Flow Bytes/s',
# ' Bwd Packet Length Mean',
# ' Fwd Avg Packets/Bulk',
# ' Subflow Fwd Bytes',
# ' Flow Packets/s',
# ' Fwd Avg Bulk Rate',
# ' act_data_pkt_fwd',
# ' Bwd URG Flags',
# ' Bwd PSH Flags',
# 'Subflow Fwd Packets',
# ' Down/Up Ratio',
# ' Flow IAT Mean',
# ' Bwd Packet Length Std',
# 'Fwd Avg Bytes/Bulk',
# ' Active Std',
# ' Destination Port',
# ' URG Flag Count',
# ' Total Length of Bwd Packets',
# ' Bwd Avg Packets/Bulk',
# ' ECE Flag Count',
# ' Bwd Avg Bytes/Bulk',
# ' Flow IAT Max',
# ' Active Min',
# ' Bwd IAT Min',
# ' Bwd IAT Max',
# ' Flow Duration',
# ' Active Max',
# ' Bwd IAT Mean',
# ' Bwd IAT Std',
# ' Average Packet Size',
# ' Avg Bwd Segment Size',
# ' Avg Fwd Segment Size',
]
Intersection123 = set(Trial_1) & set(Trial_2) & set(Trial_3)

Total = len(Trial_1)

RF_stab = len(Intersection123)/Total
print(RF_stab)
